"""initial schema

Revision ID: 6cca266108dc
Revises:
Create Date: 2026-09-09 11:33:07.475478

Autogenerated from app/models.py, then hand-corrected. Two things
autogenerate got wrong, both fixed below:

1. Missing import. Autogenerate emitted bare `app.types.GUID()` column
   types with no corresponding `import app.types` (or `app`) statement at
   all — the generated file would raise `NameError: name 'app' is not
   defined` the instant `upgrade()` ran. Fixed by importing the GUID type
   decorator directly (see import block).

2. Circular FK ordering. `outlets.admin_id -> users.id` and
   `users.outlet_id -> outlets.id` form a genuine cycle (see
   app/models.py). Autogenerate can't topologically sort that (it even
   warns "Cannot correctly sort tables ... unresolvable cycles between
   tables outlets, users" at generation time) and emitted `create_table
   ('outlets', ...)` with an inline FK to `users.id` *before* `users` is
   ever created — that statement would fail against a real empty Postgres
   with `relation "users" does not exist`. Fixed by creating `outlets`
   without the `admin_id` FK first, creating `users` (whose own FKs are
   satisfiable at that point: `outlet_id -> outlets.id` because outlets
   already exists, `created_by -> users.id` because self-referential FKs
   inline in the same CREATE TABLE are fine), then adding the
   `admin_id -> users.id` FK via a separate `ALTER TABLE` once both tables
   exist. `downgrade()` drops that added constraint before dropping
   `users`/`outlets` so the reverse direction doesn't hit the same cycle.

Everything else (column types/precision, enum columns as
`native_enum=False` VARCHAR — no CHECK constraint, since SQLAlchemy 2.0's
`Enum.create_constraint` defaults to False and app/models.py doesn't
override it, so this migration deliberately matches that: DB-level enum
values are not enforced, only application-level — flagged in the backend
report, not silently "fixed" here since that would diverge from the
model), server defaults (`is_active` true, `created_at` now()), the
`ck_*_nonneg` CHECK constraints, and the partial unique index on
`stock_movements` (`uq_stock_movements_client_id_non_sale`, scoped to
`reason <> 'sale' AND client_id IS NOT NULL`) were verified correct as
autogenerated — see backend report for the verification steps (apply to
an empty Postgres, re-run autogenerate, confirm empty diff; direct SQL
checks that the partial index actually rejects/allows the right rows).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.types import GUID


# revision identifiers, used by Alembic.
revision: str = '6cca266108dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # outlets: created WITHOUT the admin_id -> users.id FK yet (users
    # doesn't exist until the next statement) — see module docstring.
    op.create_table('outlets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('admin_id', GUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'outlet_manager', name='user_role', native_enum=False), nullable=False),
    sa.Column('outlet_id', GUID(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Close the outlets<->users cycle now that both tables exist.
    op.create_foreign_key(
        'outlets_admin_id_fkey', 'outlets', 'users', ['admin_id'], ['id'],
    )
    op.create_table('expenses',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('outlet_id', GUID(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('recorded', 'voided', name='expense_status', native_enum=False), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_expenses_amount_nonneg'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('products',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('admin_id', GUID(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('outlet_id', GUID(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='sale_discount_type', native_enum=False), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('completed', 'voided', name='sale_status', native_enum=False), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total_amount >= 0', name='ck_sales_total_amount_nonneg'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('sale_line_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('sale_id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('catalog_unit_price_at_sale', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_variance_flagged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_levels',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('outlet_id', GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'outlet_id', name='uq_stock_levels_product_outlet')
    )
    op.create_table('stock_movements',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('product_id', GUID(), nullable=False),
    sa.Column('outlet_id', GUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('sale', 'restock', 'adjustment', 'transfer', name='stock_movement_reason', native_enum=False), nullable=False),
    sa.Column('reference_id', GUID(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Partial unique index — idempotency key for adjustment/restock
    # movements only ('sale' rows share a client_id across N line items,
    # see app/models.py StockMovement docstring). Verified explicitly
    # against Postgres (not just eyeballed) — see backend report.
    op.create_index(
        'uq_stock_movements_client_id_non_sale', 'stock_movements', ['client_id'],
        unique=True,
        postgresql_where=sa.text("reason <> 'sale' AND client_id IS NOT NULL"),
        sqlite_where=sa.text("reason <> 'sale' AND client_id IS NOT NULL"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        'uq_stock_movements_client_id_non_sale', table_name='stock_movements',
        postgresql_where=sa.text("reason <> 'sale' AND client_id IS NOT NULL"),
        sqlite_where=sa.text("reason <> 'sale' AND client_id IS NOT NULL"),
    )
    op.drop_table('stock_movements')
    op.drop_table('stock_levels')
    op.drop_table('sale_line_items')
    op.drop_table('sales')
    op.drop_table('products')
    op.drop_table('expenses')
    # Drop the cross-cycle FK before dropping either side of it.
    op.drop_constraint('outlets_admin_id_fkey', 'outlets', type_='foreignkey')
    op.drop_table('users')
    op.drop_table('outlets')
